--// create iv001 table
-- Migration SQL that makes the change goes here.

CREATE TABLE iv001 
(
  USERID SMALLINT NOT NULL DEFAULT 0,
  ITEMID varchar(50) NOT NULL DEFAULT '',
  ITEMDESC varchar(255) NOT NULL DEFAULT '',
  ITEMTYPE SMALLINT NOT NULL DEFAULT 1,
  ITEMCLASSID NUMERIC(20) NOT NULL DEFAULT 0,
  CURRCOST DECIMAL NOT NULL DEFAULT 0.00,
  LISTPRICE DECIMAL NOT NULL DEFAULT 0.00,
  SHIPPINGWEIGHT DOUBLE PRECISION NOT NULL DEFAULT 0,
  IVINDEX INTEGER NOT NULL DEFAULT 0,
  IVOFFINDEX INTEGER NOT NULL DEFAULT 0,
  RETURNSINDEX INTEGER NOT NULL DEFAULT 0,
  COGSINDEX INTEGER NOT NULL DEFAULT 0,
  CREATEDATE date NOT NULL,
  BINNBR varchar(25) NOT NULL DEFAULT '',
  PRIMVENDORID INTEGER NOT NULL DEFAULT 0,
  QTYLASTORDER INTEGER NOT NULL DEFAULT 0,
  QTYONHAND BIGINT NOT NULL DEFAULT 0,
  QTYRETURNED BIGINT NOT NULL DEFAULT 0,
  QTYSOLD BIGINT NOT NULL DEFAULT 0,
  LASTORDERDT date NOT NULL,
  LASTORDERVENDORID INTEGER NOT NULL DEFAULT 0,
  a INTEGER NOT NULL DEFAULT 0,
  ISASSEMBLY SMALLINT DEFAULT 0,
  BUILDTIME SMALLINT NOT NULL DEFAULT 0,
  BUILDQTY INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT PK_IV001 PRIMARY KEY (USERID,ITEMID) USING INDEX TABLESPACE pg_default
) 
WITH (
  OIDS = FALSE
)
;

ALTER TABLE iv001 OWNER TO auctionminister;

--//@UNDO
-- SQL to undo the change goes here.

DROP TABLE iv001;
