--// create gl303 table
-- Migration SQL that makes the change goes here.

CREATE TABLE gl303 
(
  USERID SMALLINT NOT NULL DEFAULT 0,
  ACTINDEX INTEGER NOT NULL DEFAULT 0,
  YR INTEGER NOT NULL DEFAULT 0,
  CREDITBALANCE DECIMAL NOT NULL DEFAULT 0.00,
  DEBITBALANCE DECIMAL NOT NULL DEFAULT 0.00,
  CONSTRAINT PK_GL303 PRIMARY KEY (USERID,ACTINDEX,YR) USING INDEX TABLESPACE pg_default
) 
WITH (
  OIDS = FALSE
)
;

ALTER TABLE gl303 OWNER TO auctionminister;

--//@UNDO
-- SQL to undo the change goes here.

DROP TABLE gl303;