--// create sy001 table
-- Migration SQL that makes the change goes here.

CREATE SEQUENCE sy001_seq
   INCREMENT 1
   START 1;
ALTER TABLE sy001_seq OWNER TO auctionminister;

CREATE TABLE sy001 
(
  USERID SMALLINT NOT NULL DEFAULT nextval('sy001_seq'::regclass),
  USERNAME varchar(50) NOT NULL DEFAULT '',
  FIRSTNAME varchar(50) NOT NULL DEFAULT '',
  LASTNAME varchar(50) NOT NULL DEFAULT '',
  MIDDLEINITIAL char(1) NOT NULL DEFAULT '',
  PSWD varchar(20) NOT NULL DEFAULT '',
  OPTKEEPHISTORY SMALLINT NOT NULL DEFAULT 0,
  OPTVALUATIONMETHOD SMALLINT NOT NULL DEFAULT 0,
  ADDRESS1 varchar(100) NOT NULL DEFAULT '',
  ADDRESS2 varchar(100) NOT NULL DEFAULT '',
  ADDRESS3 varchar(100) NOT NULL DEFAULT '',
  CITY varchar(100) NOT NULL DEFAULT '',
  STATE varchar(25) NOT NULL DEFAULT '',
  ZIP varchar(25) NOT NULL DEFAULT '',
  PHONE varchar(25) NOT NULL DEFAULT '',
  CONSTRAINT PK_SY001 PRIMARY KEY (USERID) USING INDEX TABLESPACE pg_default,
  CONSTRAINT UK_sy001_1 UNIQUE (USERNAME) USING INDEX TABLESPACE pg_default
) 
WITH (
  OIDS = FALSE
)
;

ALTER TABLE sy001 OWNER TO auctionminister;

--//@UNDO
-- SQL to undo the change goes here.

DROP TABLE sy001;
DROP SEQUENCE sy001_seq;


