--// create g004 table
-- Migration SQL that makes the change goes here.

CREATE TABLE gl004 
(
  USERID SMALLINT NOT NULL DEFAULT 0,
  ACTINDEX INTEGER NOT NULL DEFAULT 0,
  MTH SMALLINT NOT NULL DEFAULT 0,
  YR SMALLINT NOT NULL DEFAULT 0,
  CREDITBALANCE DECIMAL NOT NULL DEFAULT 0.00,
  DEBITBALANCE DECIMAL NOT NULL DEFAULT 0.00,
  CONSTRAINT PK_GL004 PRIMARY KEY (ACTINDEX,USERID,MTH,YR) USING INDEX TABLESPACE pg_default
) 
WITH (
  OIDS = FALSE
)
;

ALTER TABLE gl004 OWNER TO auctionminister;

--//@UNDO
-- SQL to undo the change goes here.

DROP TABLE gl004;
