--// create tmp003 table
-- Migration SQL that makes the change goes here.

CREATE TABLE tmp003 
(
  TRANDATE date NOT NULL,
  REFNUM varchar(45) NOT NULL,
  REFTYPE SMALLINT DEFAULT NULL,
  OWNER1 varchar(45) DEFAULT NULL,
  OWNER2 varchar(45) DEFAULT NULL,
  ARGNAME1 varchar(100) DEFAULT NULL,
  AMOUNT DECIMAL NOT NULL DEFAULT 0.00,
  BALANCE DECIMAL NOT NULL DEFAULT 0.00,
  USERID SMALLINT DEFAULT NULL,
  ISDUP SMALLINT DEFAULT 0,
  CONSTRAINT PK_TMP003 PRIMARY KEY (REFNUM) USING INDEX TABLESPACE pg_default
) 
WITH (
  OIDS = FALSE
)
;

ALTER TABLE tmp003 OWNER TO auctionminister;

--//@UNDO
-- SQL to undo the change goes here.

DROP TABLE tmp003;