--// create sy004 table
-- Migration SQL that makes the change goes here.

CREATE SEQUENCE sy004_seq
   INCREMENT 1
   START 1;
ALTER TABLE sy004_seq OWNER TO auctionminister;

CREATE TABLE sy004 
(
  PARAMID INTEGER NOT NULL DEFAULT nextval('sy004_seq'::regclass),
  REPORTID SMALLINT NOT NULL DEFAULT 0,
  PARAMNAME varchar(25) NOT NULL DEFAULT '',
  PARAMFRIENDLYNAME varchar(100) NOT NULL DEFAULT '',
  PARAMTYPE SMALLINT NOT NULL DEFAULT 0,
  PARAMDEFAULTSTYPE SMALLINT NOT NULL DEFAULT 0,
  PARAMLENGTH SMALLINT NOT NULL DEFAULT 10,
  PARAMDEFAULTS varchar(255) NOT NULL DEFAULT '',
  CONSTRAINT PK_SY004 PRIMARY KEY (PARAMID) USING INDEX TABLESPACE pg_default,
  CONSTRAINT UK_sy004_1 UNIQUE (REPORTID,PARAMNAME) USING INDEX TABLESPACE pg_default
) 
WITH (
  OIDS = FALSE
)
;

ALTER TABLE sy004 OWNER TO auctionminister;

--//@UNDO
-- SQL to undo the change goes here.

DROP TABLE sy004;
DROP SEQUENCE sy004_seq;