--// create iv002 table
-- Migration SQL that makes the change goes here.

CREATE TABLE iv002 
(
  USERID SMALLINT NOT NULL DEFAULT 0,
  ITEMID varchar(50) NOT NULL DEFAULT '',
  VENDORID INTEGER NOT NULL DEFAULT 0,
  LASTORDERDT date NOT NULL,
  QTYLASTORDER BIGINT NOT NULL DEFAULT 0,
  VENDORITEM varchar(50) NOT NULL DEFAULT '',
  CONSTRAINT PK_IV002 PRIMARY KEY (ITEMID,USERID,VENDORID) USING INDEX TABLESPACE pg_default
) 
WITH (
  OIDS = FALSE
)
;

ALTER TABLE iv002 OWNER TO auctionminister;

--//@UNDO
-- SQL to undo the change goes here.

DROP TABLE iv002;